# Generated by Django 5.0 on 2023-12-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hobby',
            field=models.CharField(blank=True, choices=[('Movies', 'Movies'), ('Games', 'Games'), ('Books', 'Books')], max_length=50),
        ),
    ]
