# Generated by Django 5.0 on 2023-12-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='file',
            new_name='uploading_file',
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file_id',
            field=models.CharField(default='88048a045305', editable=False, max_length=255),
        ),
    ]
