# Generated by Django 5.0 on 2023-12-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_files_sharedfiles_sharefiles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedfiles',
            name='owner',
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file_id',
            field=models.CharField(default='d68ae87687ee', editable=False, max_length=255),
        ),
    ]
